# Jekyll Configuration for GitHub Pages
title: "Мій Сайт"
description: "Красивий сайт з чорним фоном, плаваючими білими шарами та сучасним дизайном"
author: "ST Developer"
email: "your-email@example.com"

# Build settings
markdown: kramdown
highlighter: rouge
syntax_highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - README_DJANGO.md
  - requirements.txt
  - manage.py
  - db.sqlite3
  - mysite/
  - main/
  - components/
  - styles/
  - photo_2025-09-09_15-52-44.jpg
  - .gitignore
  - .git/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - .bundle/
  - node_modules/
  - static/
  - templates/

# Include files
include:
  - _redirects
  - assets/css/style.css
  - assets/js/main.js

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Site settings
url: "https://your-username.github.io"
baseurl: "/st"

# Social links
social:
  github: your-username

# Build settings
safe: true
lsi: false
excerpt_separator: "\n\n"
incremental: false

# GitHub Pages specific settings
github: [metadata]
repository: your-username/st

# Liquid settings
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false
