# Generated by Django 4.2.7

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Мій Сайт', max_length=200)),
                ('site_description', models.TextField(default='Красивий сайт з чорним фоном, плаваючими білими шарами та сучасним дизайном')),
                ('hero_section_title', models.CharField(default='Преміум товар', max_length=200)),
                ('hero_section_description', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#ff8c42', help_text='Основний колір (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#4ecdc4', help_text='Додатковий колір (hex)', max_length=7)),
                ('hero_section_width_pc', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('additional_products_width_pc', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='ColorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва кольору (наприклад: Помаранчевий)', max_length=50)),
                ('hex_code', models.CharField(help_text='Hex код кольору (наприклад: #ff8c42)', max_length=7)),
                ('image', models.ImageField(help_text='Зображення для цього кольору', upload_to='color_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок відображення')),
            ],
            options={
                'verbose_name': 'Кольоровий варіант',
                'verbose_name_plural': 'Кольорові варіанти',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuantityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Кількість (наприклад: 21)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок відображення')),
            ],
            options={
                'verbose_name': 'Варіант кількості',
                'verbose_name_plural': 'Варіанти кількості',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Преміум товар', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=2800.0, max_digits=10)),
                ('currency', models.CharField(default='грн', max_length=10)),
                ('add_to_cart_text', models.CharField(default='В кошик', max_length=50)),
                ('remove_from_cart_text', models.CharField(default='Прибрати', max_length=50)),
                ('show_premium_label', models.BooleanField(default=True)),
                ('premium_label_text', models.CharField(default='Преміум товар', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Головний товар',
                'verbose_name_plural': 'Головний товар',
            },
        ),
        migrations.CreateModel(
            name='AdditionalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Назва товару', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Ціна товару', max_digits=10)),
                ('currency', models.CharField(default='грн', max_length=10)),
                ('image', models.ImageField(help_text='Зображення товару', upload_to='additional_products/')),
                ('add_to_cart_text', models.CharField(default='Додати в кошик', max_length=50)),
                ('remove_from_cart_text', models.CharField(default='Відняти з кошика', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок відображення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Додатковий товар',
                'verbose_name_plural': 'Додаткові товари',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalProductsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Додаткові товари', max_length=200)),
                ('add_all_text', models.CharField(default='Додати всі', max_length=50)),
                ('remove_all_text', models.CharField(default='Прибрати всі', max_length=50)),
                ('show_section', models.BooleanField(default=True)),
                ('max_products_per_row', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування додаткових товарів',
                'verbose_name_plural': 'Налаштування додаткових товарів',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Номер телефону', max_length=20)),
                ('email', models.EmailField(help_text='Email адреса', max_length=254)),
                ('address', models.TextField(help_text='Адреса')),
                ('working_hours', models.CharField(help_text='Графік роботи', max_length=100)),
                ('instagram', models.URLField(blank=True, help_text='Instagram URL')),
                ('facebook', models.URLField(blank=True, help_text='Facebook URL')),
                ('telegram', models.URLField(blank=True, help_text='Telegram URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контактна інформація',
                'verbose_name_plural': 'Контактна інформація',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Назва послуги', max_length=200)),
                ('description', models.TextField(help_text='Опис послуги')),
                ('icon', models.CharField(default='🌟', help_text='Іконка (emoji або CSS клас)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок відображення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order'],
            },
        ),
    ]
