# Jekyll Configuration for Demo Site
title: "Мій Демо Сайт"
description: "Демонстраційна версія сайту з чорним фоном, плаваючими білими шарами та сучасним дизайном"
baseurl: "/st-demo" # Adjust if your GitHub Pages project is in a subdirectory
url: "https://yourusername.github.io" # Replace with your GitHub username

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules

# Include files
include:
  - _redirects

# Collections
collections:
  products:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
author: "Your Name"
social:
  github: yourusername
  email: your.email@example.com